#!/usr/bin/env node
// 01_apply_schema — apply the cleaned db/yandex/sql/*.sql foundation to the
// Yandex Managed PostgreSQL target, in lexical file order, with safety gates.
//
// SAFETY:
//   - Schema only (DDL/functions/triggers). Does NOT import data.
//   - NEVER prints DSN, password, cert contents, or full host.
//   - Forbidden-statement scan (comment-aware) runs BEFORE any apply.
//   - Real apply requires: NO --dry-run AND env ALLOW_APPLY_SCHEMA=true.
//   - Real apply additionally requires an EMPTY target (0 user tables; only
//     public/auth non-system schemas). Otherwise: fail, do not continue.
//   - Each SQL file is applied in its own transaction (BEGIN/COMMIT;
//     ROLLBACK + STOP on first error — no further files).
//   - Writes docs/yandex-migration/08_SCHEMA_APPLY_RESULT.md every run.
//
// Usage:
//   npm run prod-to-yandex:schema -- --dry-run
//   npm run prod-to-yandex:schema -- --from 03_tables.sql --to 06_indexes_constraints.sql --dry-run
//   ALLOW_APPLY_SCHEMA=true npm run prod-to-yandex:schema        # real apply (authorised only)
//
// Env: scripts/prod-to-yandex/.env.prod-to-yandex (see .example)

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { parseArgs } from 'node:util';
import {
  loadEnv, env, maskHost, safeErr, resolveCa, connectStrict,
  listSqlFiles, forbiddenScan, SQL_DIR, DOC_DIR,
} from './_lib.mjs';

const REPORT = join(DOC_DIR, '08_SCHEMA_APPLY_RESULT.md');

const STATUS = {
  DRY: 'SCHEMA_DRY_RUN_OK',
  OK: 'SCHEMA_APPLY_OK',
  FAILED: 'SCHEMA_APPLY_FAILED',
};

const ALLOWED_NON_SYSTEM_SCHEMAS = new Set(['public', 'auth']);

function applyRange(files, from, to) {
  let lo = 0;
  let hi = files.length - 1;
  if (from) {
    lo = files.indexOf(from);
    if (lo < 0) throw new Error(`--from "${from}" not found in db/yandex/sql/`);
  }
  if (to) {
    hi = files.indexOf(to);
    if (hi < 0) throw new Error(`--to "${to}" not found in db/yandex/sql/`);
  }
  if (lo > hi) throw new Error(`--from "${from}" is after --to "${to}"`);
  return files.slice(lo, hi + 1);
}

function writeReport(r) {
  mkdirSync(DOC_DIR, { recursive: true });
  const L = [];
  L.push('# 08. SCHEMA APPLY RESULT');
  L.push('');
  L.push('> Generated by `scripts/prod-to-yandex/01_apply_schema.mjs`.');
  L.push('> Overwritten on every run. No data is ever imported by this script.');
  L.push('');
  L.push(`- Run (UTC): ${r.ts}`);
  L.push(`- Mode: **${r.mode}**`);
  L.push(`- Target database: ${r.targetDb}`);
  L.push(`- Target user: ${r.targetUser}`);
  L.push(`- Range: ${r.from || '(start)'} → ${r.to || '(end)'}`);
  L.push('');
  L.push('## SQL files planned');
  L.push('');
  r.planned.length ? r.planned.forEach((f, i) => L.push(`${i + 1}. ${f}`)) : L.push('_none_');
  L.push('');
  L.push('## SQL files applied');
  L.push('');
  r.applied.length ? r.applied.forEach((f) => L.push(`- ${f}`)) : L.push('_none_');
  L.push('');
  L.push('## SQL files skipped');
  L.push('');
  r.skipped.length ? r.skipped.forEach((f) => L.push(`- ${f}`)) : L.push('_none_');
  L.push('');
  L.push('## Forbidden statement scan');
  L.push('');
  L.push(`- Scanned files: ${r.scanned.length} (${r.scanned.join(', ') || 'none'})`);
  if (r.forbidden.length === 0) {
    L.push('- Result: **clean** — no executable forbidden statements '
      + '(CREATE EXTENSION / CREATE ROLE / ALTER ROLE / ALTER SYSTEM / '
      + 'session_replication_role / GRANT TO authenticated|anon / service_role / '
      + 'authenticator). Comment-only matches ignored.');
  } else {
    L.push('- Result: **VIOLATIONS FOUND**');
    r.forbidden.forEach((h) => L.push(`  - ❌ ${h.file}: ${h.rule} — \`${h.sample}\``));
  }
  L.push('');
  L.push('## Target emptiness precheck');
  L.push('');
  L.push(`- ${r.emptiness}`);
  L.push('');
  L.push('## Errors');
  L.push('');
  r.errors.length ? r.errors.forEach((e) => L.push(`- ❌ ${e}`)) : L.push('_none_');
  L.push('');
  L.push('## Final status');
  L.push('');
  L.push('```');
  L.push(r.status);
  L.push('```');
  L.push('');
  writeFileSync(REPORT, L.join('\n'), 'utf8');
}

async function main() {
  loadEnv();

  const { values } = parseArgs({
    options: {
      'dry-run': { type: 'boolean', default: false },
      from: { type: 'string' },
      to: { type: 'string' },
    },
  });
  const dryRun = values['dry-run'] === true;
  const ts = new Date().toISOString();

  const r = {
    ts,
    mode: dryRun ? 'dry-run' : 'apply',
    targetDb: dryRun ? '(not connected — dry-run)' : '(unknown)',
    targetUser: dryRun ? '(not connected — dry-run)' : '(unknown)',
    from: values.from || '',
    to: values.to || '',
    planned: [],
    applied: [],
    skipped: [],
    scanned: [],
    forbidden: [],
    emptiness: dryRun ? 'skipped (dry-run — no connection)' : 'not run',
    errors: [],
    status: STATUS.FAILED,
  };

  const allFiles = listSqlFiles();
  if (allFiles.length === 0) {
    r.errors.push('db/yandex/sql/ has no .sql files.');
    writeReport(r);
    console.error('✗ db/yandex/sql/ has no .sql files.');
    process.exit(2);
  }

  let selected;
  try {
    selected = applyRange(allFiles, values.from, values.to);
  } catch (e) {
    r.errors.push(e.message);
    writeReport(r);
    console.error(`✗ ${e.message}`);
    process.exit(2);
  }
  r.planned = selected;
  r.skipped = allFiles.filter((f) => !selected.includes(f));

  // ---- forbidden-statement scan (ALL files; comment-aware) ----
  r.scanned = allFiles;
  r.forbidden = forbiddenScan(allFiles);

  console.log(`▶ prod-to-yandex schema apply ${dryRun ? '(DRY-RUN)' : ''}`);
  console.log(`  sql dir : db/yandex/sql/`);
  console.log(`  planned : ${selected.length} (${selected[0]} … ${selected[selected.length - 1]})`);
  selected.forEach((f, i) => console.log(`   ${String(i + 1).padStart(2)}. ${f}`));
  console.log(`  forbidden scan: ${r.forbidden.length === 0 ? 'clean' : 'VIOLATIONS'}`);

  if (r.forbidden.length > 0) {
    r.errors.push('Forbidden executable statement(s) detected — refusing to apply.');
    r.status = STATUS.FAILED;
    writeReport(r);
    console.error('\n✗ SCHEMA_APPLY_FAILED — forbidden statements:');
    r.forbidden.forEach((h) => console.error(`  ✗ ${h.file}: ${h.rule}`));
    console.error(`  report: ${REPORT}`);
    process.exit(1);
  }

  // ---- DRY-RUN: never connect, never apply ----
  if (dryRun) {
    r.status = STATUS.DRY;
    writeReport(r);
    console.log('\n✓ SCHEMA_DRY_RUN_OK — no DB connection, nothing applied.');
    console.log(`  report: ${REPORT}`);
    process.exit(0);
  }

  // ---- Real apply: two-key guard ----
  if (env('ALLOW_APPLY_SCHEMA') !== 'true') {
    r.errors.push('Real apply refused: ALLOW_APPLY_SCHEMA != true.');
    r.status = STATUS.FAILED;
    writeReport(r);
    console.error('✗ Real apply refused: ALLOW_APPLY_SCHEMA != true.');
    console.error('  Set ALLOW_APPLY_SCHEMA=true AND re-run WITHOUT --dry-run only');
    console.error('  when the operator authorises it (05_CUTOVER_RULES.md).');
    console.error(`  report: ${REPORT}`);
    process.exit(2);
  }

  const yaUrl = env('YANDEX_DATABASE_URL');
  if (!yaUrl) {
    r.errors.push('YANDEX_DATABASE_URL not set.');
    r.status = STATUS.FAILED;
    writeReport(r);
    console.error('✗ YANDEX_DATABASE_URL not set.');
    process.exit(2);
  }
  const ca = resolveCa();
  if (!ca.ok) {
    r.errors.push(`Yandex CA unavailable (${ca.reason}); verify-full required — refusing.`);
    r.status = STATUS.FAILED;
    writeReport(r);
    console.error(`✗ Yandex CA unavailable: ${ca.reason} (verify-full required).`);
    process.exit(2);
  }

  console.log(`\n  target  : host=${maskHost(yaUrl)} (verify-full)`);

  let client;
  try {
    client = await connectStrict(yaUrl, ca.pem, 'prod-to-yandex-apply-schema');
  } catch (e) {
    r.errors.push(`connection failed: ${safeErr(e)}`);
    r.status = STATUS.FAILED;
    writeReport(r);
    console.error(`✗ connection failed: ${safeErr(e)}`);
    process.exit(1);
  }

  try {
    const q = async (sql) => (await client.query(sql)).rows;
    const [{ current_database }] = await q('SELECT current_database()');
    const [{ current_user }] = await q('SELECT current_user');
    r.targetDb = String(current_database);
    r.targetUser = String(current_user);

    // ---- target emptiness precheck (real apply only) ----
    const userTblRows = await q(
      "SELECT schemaname, count(*)::int AS n FROM pg_tables " +
      "WHERE schemaname NOT IN ('pg_catalog','information_schema') " +
      "GROUP BY schemaname ORDER BY schemaname");
    const userTableTotal = userTblRows.reduce((a, x) => a + x.n, 0);
    const nonSysSchemas = (await q(
      "SELECT nspname FROM pg_namespace " +
      "WHERE nspname NOT IN ('pg_catalog','information_schema','pg_toast') " +
      "AND nspname NOT LIKE 'pg_temp_%' AND nspname NOT LIKE 'pg_toast_temp_%' " +
      "ORDER BY nspname")).map((x) => x.nspname);
    const disallowed = nonSysSchemas.filter((s) => !ALLOWED_NON_SYSTEM_SCHEMAS.has(s));

    if (userTableTotal > 0 || disallowed.length > 0) {
      r.emptiness =
        `FAIL — user tables=${userTableTotal} ` +
        `(${userTblRows.map((x) => `${x.schemaname}=${x.n}`).join(', ') || 'none'}); ` +
        `non-system schemas=[${nonSysSchemas.join(', ')}]` +
        (disallowed.length ? `; disallowed=[${disallowed.join(', ')}]` : '');
      if (userTableTotal > 0) r.errors.push(`Target not empty: ${userTableTotal} user table(s) — refusing real apply.`);
      if (disallowed.length) r.errors.push(`Unexpected non-system schema(s): ${disallowed.join(', ')} — refusing real apply.`);
      r.status = STATUS.FAILED;
      writeReport(r);
      console.error('✗ SCHEMA_APPLY_FAILED — target emptiness precheck failed.');
      console.error(`  ${r.emptiness}`);
      await client.end().catch(() => {});
      process.exit(1);
    }
    r.emptiness =
      `OK — 0 user tables; non-system schemas=[${nonSysSchemas.join(', ') || 'none'}] ` +
      `(allowed: public/auth)`;
    console.log(`  emptiness: OK (0 user tables; schemas=[${nonSysSchemas.join(', ') || 'none'}])`);

    // ---- apply selected files, each in its own transaction ----
    for (const f of selected) {
      const sql = readFileSync(join(SQL_DIR, f), 'utf8');
      process.stdout.write(`  applying ${f} … `);
      try {
        await client.query('BEGIN');
        await client.query(sql);
        await client.query('COMMIT');
        r.applied.push(f);
        console.log('ok');
      } catch (e) {
        await client.query('ROLLBACK').catch(() => {});
        r.errors.push(`STOPPED at ${f}: ${safeErr(e)}`);
        console.log('FAILED');
        r.status = STATUS.FAILED;
        writeReport(r);
        console.error(`\n✗ SCHEMA_APPLY_FAILED at ${f}: ${safeErr(e)}`);
        console.error(`  report: ${REPORT}`);
        await client.end().catch(() => {});
        process.exit(1); // do not continue to the next file
      }
    }
  } finally {
    await client.end().catch(() => {});
  }

  r.status = STATUS.OK;
  writeReport(r);
  console.log(`\n✓ SCHEMA_APPLY_OK — ${r.applied.length} file(s) applied. No data imported.`);
  console.log(`  report: ${REPORT}`);
  process.exit(0);
}

main().catch((e) => {
  console.error(`✗ unexpected error: ${safeErr(e)}`);
  if (process.env.DEBUG === 'true' && e?.stack) console.error(e.stack);
  process.exit(1);
});
