#!/usr/bin/env node
// 05_verify_yandex — post-import data consistency check on the Yandex target.
//
// =============================== SAFETY ====================================
//  - Read-only against Yandex (verify-full + raw parsers + UTC/ISO).
//  - Source of truth = the PROD Supabase export manifest in EXPORT_DIR.
//  - OLD_SUPABASE_DB_URL forbidden (assertNoOldEnv, exit 7).
//  - Compares: row counts (all tables) vs manifest, PK duplicate checks, FK
//    consistency, auth/public user consistency, server-side + chunked raw-safe
//    checksums. Explicitly verifies the strict table list, tender_registry
//    duplicates baseline, and boq_items_audit inflation == 0.
//  - Writes docs/yandex-migration/13_YANDEX_VERIFY_RESULT.md with final status
//    YANDEX_VERIFY_OK / _OK_WITH_WARNINGS / _FAILED.
//  - No stack trace unless DEBUG=true. Exit: 0 ok/warn · 1 failed · 2 precond.
// ===========================================================================

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

import {
  loadEnv, env, requireEnv, getExportDir, getYandexClient, resolveCa,
  tag, parseCliArgs, requireExportFiles, fatal, assertNoOldEnv,
  assertTemporalRawParsers, DOC_DIR, safeErr,
} from './_lib.mjs';
import {
  IMPORT_ORDER, FK_CHECKS, CHECKSUM_TABLES, STRICT_VERIFY_TABLES,
  HEAVY_CHECKSUM_TABLES, defaultOrderBy,
} from './_tables.mjs';
import { countRows, tableExists, readNdjson } from './_copy.mjs';
import { tableChecksumSql, chunkedTableChecksum, HEAVY_CHECKSUM_CHUNK } from './_checksums.mjs';

loadEnv();

const REPORT = join(DOC_DIR, '13_YANDEX_VERIFY_RESULT.md');
const STATUS = { OK: 'YANDEX_VERIFY_OK', WARN: 'YANDEX_VERIFY_OK_WITH_WARNINGS', FAILED: 'YANDEX_VERIFY_FAILED' };

const { values } = parseCliArgs({
  name: '05_verify_yandex.mjs',
  description: 'Verify Yandex row counts / FK / checksums vs the PROD export.',
  options: {
    'export-dir': { type: 'string', default: '', describe: 'Override EXPORT_DIR env' },
  },
});
const exportDir = values['export-dir'] || env('EXPORT_DIR') || getExportDir();

function bail(status, friendly, exitCode) {
  writeReport({ status, generated_at: new Date().toISOString(), note: friendly });
  console.error(`✗ ${status}${friendly ? ` — ${friendly}` : ''}`);
  console.error(`  report: ${REPORT}`);
  process.exit(exitCode);
}

function writeReport(report) {
  mkdirSync(DOC_DIR, { recursive: true });
  const L = [];
  L.push('# 13. YANDEX VERIFY RESULT');
  L.push('');
  L.push('> Generated by `scripts/prod-to-yandex/05_verify_yandex.mjs` (read-only).');
  L.push('> Overwritten on every run. Source of truth = PROD Supabase export manifest.');
  L.push('');
  L.push(`- Run (UTC): ${report.generated_at}`);
  if (report.note) L.push(`- Note: ${report.note}`);
  L.push('');
  if (report.row_counts) {
    L.push('## Row counts (Yandex vs PROD export manifest)');
    L.push('');
    L.push('| Table | PROD | Yandex | Severity | Note |');
    L.push('|---|---:|---:|---|---|');
    for (const r of report.row_counts) {
      L.push(`| ${r.table} | ${r.prod ?? '-'} | ${r.yandex} | ${r.severity} | ${r.note ?? ''} |`);
    }
    L.push('');
  }
  if (report.fk_violations) {
    L.push('## FK consistency');
    L.push('');
    L.push('| FK | Orphans | OK |');
    L.push('|---|---:|---|');
    for (const r of report.fk_violations) L.push(`| \`${r.fk}\` | ${r.orphans} | ${r.ok ? '✓' : '✗'} |`);
    L.push('');
  }
  if (report.orphan_checks) {
    L.push('## Auth/public user consistency');
    L.push('');
    L.push('| Check | Count | OK |');
    L.push('|---|---:|---|');
    for (const r of report.orphan_checks) L.push(`| ${r.name} | ${r.count} | ${r.ok ? '✓' : '✗'} |`);
    L.push('');
  }
  if (report.checksums) {
    L.push('## Table checksums (md5 of stable text aggregate; raw-type-safe)');
    L.push('');
    L.push('> `auth.users` is verified separately by 06_verify_passwords (encrypted_password never printed).');
    L.push('');
    L.push('| Table | Status | Note |');
    L.push('|---|---|---|');
    for (const c of report.checksums) {
      const m = c.status === 'match' ? '✓' : c.status === 'mismatch' ? '✗' : '⚠';
      let note = c.note ?? '';
      if (c.table === 'tenders' && c.status === 'mismatch') {
        note = (note ? note + ' — ' : '')
          + 'KNOWN: grand-total recalc triggers re-stamped tenders.updated_at '
          + 'during a pre-fix import (only updated_at differs; data is correct). '
          + 'Fixed at root cause in 04_import_yandex; targeted repair: '
          + 'npm run prod-to-yandex:repair-tenders-updated-at (see '
          + 'docs/yandex-migration/17_TENDERS_UPDATED_AT_REPAIR_RESULT.md).';
      }
      L.push(`| public.${c.table} | ${m} ${c.status} | ${note.replace(/\|/g, '\\|')} |`);
    }
    L.push('');
  }
  if (report.registry_duplicates) {
    const d = report.registry_duplicates;
    L.push('## tender_registry duplicate baseline');
    L.push('');
    L.push('| Group | PROD | Yandex | OK |');
    L.push('|---|---:|---:|---|');
    L.push(`| by tender_number | ${d.prod.by_tender_number} | ${d.yandex.by_tender_number} | ${d.ok ? '✓' : '✗'} |`);
    L.push(`| by title+client+area | ${d.prod.by_title_client_area} | ${d.yandex.by_title_client_area} | ${d.ok ? '✓' : '✗'} |`);
    L.push('');
  }
  if (report.audit_delta) {
    const a = report.audit_delta;
    L.push('## boq_items_audit inflation');
    L.push('');
    L.push(`- PROD export rows: ${a.prod}`);
    L.push(`- Yandex rows: ${a.yandex}`);
    L.push(`- Inflation: ${a.inflation} ${a.ok ? '✓ (must be ≤ 0)' : '✗'}`);
    if (a.note) L.push(`- ${a.note}`);
    L.push('');
  }
  if (report.audit_history) {
    const h = report.audit_history;
    L.push('## Audit history integrity');
    L.push('');
    L.push('> `boq_items_audit.boq_item_id` has NO enforced FK by design (audit/');
    L.push('> history keeps DELETE rows for removed boq_items — PROD has no such');
    L.push('> FK). Integrity = orphan baseline equality, not FK enforcement.');
    L.push('');
    L.push('| Metric | PROD export baseline | Yandex target | OK |');
    L.push('|---|---:|---:|---|');
    L.push(`| total audit rows | ${h.prod.total} | ${h.yandex.total} | ${h.total_ok ? '✓' : '✗'} |`);
    L.push(`| orphan audit rows | ${h.prod.orphan_rows} | ${h.yandex.orphan_rows} | ${h.orphan_ok ? '✓' : '✗'} |`);
    L.push(`| unique orphan boq_item_id | ${h.prod.distinct_orphan} | ${h.yandex.distinct_orphan} | ${h.distinct_ok ? '✓' : '✗'} |`);
    L.push('');
    L.push(`- Result: ${h.ok ? '✓ Yandex matches PROD audit baseline' : '✗ audit baseline mismatch — investigate (no auto re-import)'}`);
    if (h.note) L.push(`- ${h.note}`);
    L.push('');
  }
  if (report.warnings && report.warnings.length) {
    L.push('## Warnings');
    L.push('');
    for (const w of report.warnings) L.push(`- ⚠️ ${w}`);
    L.push('');
  }
  L.push('## Final status');
  L.push('');
  L.push('```');
  L.push(report.status);
  L.push('```');
  L.push('');
  writeFileSync(REPORT, L.join('\n'), 'utf8');
}

async function main() {
  try { assertNoOldEnv(); } catch (e) { console.error(`✗ ${e.message}`); process.exit(7); }

  if (!existsSync(join(exportDir, 'manifest.json'))) {
    bail(STATUS.FAILED,
      `manifest.json not found in ${exportDir} — run \`npm run prod-to-yandex:export\` then \`:import\` before verify.`,
      2);
  }
  const manifest = JSON.parse(readFileSync(join(exportDir, 'manifest.json'), 'utf8'));
  if (manifest.source_label !== 'PROD_SUPABASE') {
    bail(STATUS.FAILED, `manifest.source_label=${manifest.source_label}; expected PROD_SUPABASE.`, 2);
  }

  let yaUrl;
  try { yaUrl = requireEnv('YANDEX_DATABASE_URL'); }
  catch (e) { bail(STATUS.FAILED, e.message, 2); }
  const ca = resolveCa();
  if (!ca.ok) bail(STATUS.FAILED, `Yandex CA unavailable (${ca.reason}); verify-full required.`, 2);

  let client;
  try {
    client = await getYandexClient(yaUrl, ca.pem, { applicationName: 'prod-to-yandex-verify' });
  } catch (e) {
    bail(STATUS.FAILED, `Yandex unreachable: ${safeErr(e)}`, 1);
  }

  const report = {
    generated_at: new Date().toISOString(),
    row_counts: [], fk_violations: [], orphan_checks: [], checksums: [],
    registry_duplicates: null, audit_delta: null, audit_history: null,
    warnings: [], status: 'PENDING',
  };

  try {
    const temporal = await assertTemporalRawParsers(client);
    console.log(`${tag('YA')} raw-parser self-check ✓ (tstz=${temporal.timestamptz}, UTC/ISO)`);

    const strict = new Set(STRICT_VERIFY_TABLES);

    // ---- Row counts ----
    for (const table of IMPORT_ORDER) {
      const prod = manifest.row_counts?.[`public.${table}`] ?? null;
      let ya = null;
      try {
        if (!(await tableExists(client, 'public', table))) { report.warnings.push(`public.${table}: missing on Yandex`); continue; }
        ya = await countRows(client, 'public', table);
      } catch (e) { report.warnings.push(`public.${table}: count failed (${safeErr(e)})`); continue; }
      let severity, note = null;
      if (prod == null) { severity = 'WARN'; note = 'no PROD count in manifest'; }
      else if (ya < prod) { severity = 'FAIL'; note = `missing ${prod - ya} rows`; }
      else if (ya > prod) { severity = 'FAIL'; note = `${ya - prod} extra rows (target must equal PROD)`; }
      else severity = 'OK';
      report.row_counts.push({ table, prod, yandex: ya, severity, note });
      const mark = severity === 'FAIL' ? '✗' : severity === 'WARN' ? '⚠' : '✓';
      console.log(`${tag('YA')} ${mark} public.${table}: prod=${prod ?? '-'} yandex=${ya}${note ? ' — ' + note : ''}`);
    }
    // auth row counts.
    for (const a of ['users', 'identities']) {
      const prod = manifest.row_counts?.[`auth.${a}`] ?? null;
      if (prod == null) continue;
      try {
        if (!(await tableExists(client, 'auth', a))) { report.warnings.push(`auth.${a}: missing on Yandex`); continue; }
        const ya = await countRows(client, 'auth', a);
        const severity = ya === prod ? 'OK' : (ya < prod ? 'FAIL' : 'FAIL');
        report.row_counts.push({ table: `auth.${a}`, prod, yandex: ya, severity, note: ya === prod ? null : 'must equal PROD' });
        console.log(`${tag('YA')} ${ya === prod ? '✓' : '✗'} auth.${a}: prod=${prod} yandex=${ya}`);
      } catch (e) { report.warnings.push(`auth.${a}: count failed (${safeErr(e)})`); }
    }

    // ---- FK consistency ----
    for (const fk of FK_CHECKS) {
      try {
        if (!(await tableExists(client, 'public', fk.table))) continue;
        const { rows: [{ n }] } = await client.query(`
          SELECT COUNT(*)::int AS n
            FROM "public"."${fk.table}" c
            LEFT JOIN "${fk.refSchema}"."${fk.refTable}" p ON p."${fk.refColumn}" = c."${fk.column}"
           WHERE c."${fk.column}" IS NOT NULL AND p."${fk.refColumn}" IS NULL
        `);
        const ok = n === 0;
        report.fk_violations.push({ fk: `${fk.table}.${fk.column} → ${fk.refSchema}.${fk.refTable}.${fk.refColumn}`, orphans: n, ok });
        console.log(`${tag('YA')} ${ok ? '✓' : '✗'} FK ${fk.table}.${fk.column} → ${fk.refSchema}.${fk.refTable}.${fk.refColumn}: ${n} orphans`);
      } catch (e) { report.warnings.push(`FK ${fk.table}.${fk.column}: ${safeErr(e)}`); }
    }

    // ---- Auth/public user consistency ----
    try {
      const { rows: [a] } = await client.query(`
        SELECT COUNT(*)::int AS n FROM public.users pu
        LEFT JOIN auth.users au ON au.id = pu.id WHERE au.id IS NULL`);
      report.orphan_checks.push({ name: 'public.users without auth.users', count: a.n, ok: a.n === 0 });
      const { rows: [b] } = await client.query(`
        SELECT COUNT(*)::int AS n FROM auth.users au
        LEFT JOIN public.users pu ON pu.id = au.id WHERE pu.id IS NULL`);
      report.orphan_checks.push({ name: 'auth.users without public.users (tolerated)', count: b.n, ok: true });
      console.log(`${tag('YA')} user consistency: public→auth orphans=${a.n}, auth→public=${b.n}`);
    } catch (e) { report.warnings.push(`user consistency: ${safeErr(e)}`); }

    // ---- Checksums (strict tables explicitly covered) ----
    const manifestByTable = new Map((manifest.tables ?? []).map((t) => [`${t.schema}.${t.table}`, t]));
    const checksumTables = [...new Set([...CHECKSUM_TABLES, ...STRICT_VERIFY_TABLES.filter((t) => t !== 'users' ? false : false)])];
    for (const table of CHECKSUM_TABLES) {
      const me = manifestByTable.get(`public.${table}`);
      if (!me) { report.warnings.push(`public.${table}: not in manifest, skipping checksum`); continue; }
      const prodRows = me.rows ?? 0;
      const yaRows = report.row_counts.find((r) => r.table === table)?.yandex ?? null;
      if (prodRows === 0 && (yaRows ?? 0) === 0) {
        report.checksums.push({ table, status: 'match', note: 'empty (0 rows) — PROD == Yandex' });
        console.log(`${tag('YA')} ✓ checksum public.${table}: match — empty`);
        continue;
      }
      const prodChecksum = me.sql_checksum ?? null;
      let yaChecksum = null;
      try {
        const orderBy = defaultOrderBy(table);
        if (me.sql_checksum_mode === 'chunked' || HEAVY_CHECKSUM_TABLES.has(table)) {
          yaChecksum = await chunkedTableChecksum(client, {
            schema: 'public', table, orderBy,
            chunkSize: me.sql_checksum_chunk_size || HEAVY_CHECKSUM_CHUNK,
          });
        } else {
          const { rows: [c] } = await client.query(tableChecksumSql('public', table, orderBy));
          yaChecksum = c?.checksum ?? null;
        }
      } catch (e) {
        report.checksums.push({ table, status: 'mismatch', note: `Yandex checksum compute failed (${safeErr(e)})` });
        console.log(`${tag('YA')} ✗ checksum public.${table}: compute failed`);
        continue;
      }
      let status, note = null;
      if (!prodChecksum) { status = 'mismatch'; note = 'no PROD checksum in manifest for a non-empty table — re-run :export'; }
      else if (prodChecksum === yaChecksum) status = 'match';
      else { status = 'mismatch'; note = 'Yandex content differs from PROD export'; }
      report.checksums.push({ table, status, note });
      console.log(`${tag('YA')} ${status === 'match' ? '✓' : '✗'} checksum public.${table}: ${status}${note ? ' — ' + note : ''}`);
    }

    // ---- tender_registry duplicate baseline ----
    try {
      const { rows: [r] } = await client.query(`
        SELECT
          (SELECT COUNT(*)::int FROM (
              SELECT tender_number FROM public.tender_registry
               WHERE tender_number IS NOT NULL GROUP BY tender_number HAVING COUNT(*) > 1) t) AS by_tender_number,
          (SELECT COUNT(*)::int FROM (
              SELECT title, client_name, area FROM public.tender_registry
               WHERE tender_number IS NULL GROUP BY title, client_name, area HAVING COUNT(*) > 1) t) AS by_title_client_area
      `);
      const prodDup = manifest.tender_registry_duplicates ?? { by_tender_number: 0, by_title_client_area: 0 };
      const yaDup = { by_tender_number: r.by_tender_number, by_title_client_area: r.by_title_client_area };
      const ok = yaDup.by_tender_number <= prodDup.by_tender_number && yaDup.by_title_client_area <= prodDup.by_title_client_area;
      report.registry_duplicates = { prod: prodDup, yandex: yaDup, ok };
      console.log(`${tag('YA')} ${ok ? '✓' : '✗'} tender_registry duplicates: prod(${prodDup.by_tender_number}/${prodDup.by_title_client_area}) yandex(${yaDup.by_tender_number}/${yaDup.by_title_client_area})`);
    } catch (e) { report.warnings.push(`registry duplicate check: ${safeErr(e)}`); }

    // ---- boq_items_audit inflation == 0 ----
    try {
      const prodAudit = manifest.row_counts?.['public.boq_items_audit'] ?? 0;
      const { rows: [a] } = await client.query('SELECT COUNT(*)::int AS n FROM public.boq_items_audit');
      const inflation = a.n - prodAudit;
      const ok = inflation <= 0;
      report.audit_delta = { prod: prodAudit, yandex: a.n, inflation, ok };
      if (!ok) {
        const boq = manifest.row_counts?.['public.boq_items'] ?? 0;
        report.audit_delta.note = inflation === boq
          ? `Inflation == imported boq_items (${boq}) — audit trigger fired during import. Re-import with ALLOW_DISABLE_IMPORT_TRIGGERS=true.`
          : `Yandex has ${inflation} more audit rows than PROD export — investigate.`;
      }
      console.log(`${tag('YA')} ${ok ? '✓' : '✗'} boq_items_audit: prod=${prodAudit} yandex=${a.n} inflation=${inflation}`);
    } catch (e) { report.warnings.push(`audit inflation check: ${safeErr(e)}`); }

    // ---- Audit history integrity (NOT an FK check) ----
    // boq_items_audit keeps DELETE history for removed boq_items. PROD has no
    // FK boq_items_audit.boq_item_id → boq_items. We verify the Yandex audit
    // baseline (total / orphan / distinct-orphan) equals the PROD export
    // baseline computed from the NDJSON, instead of failing on orphans.
    try {
      const auditPath = join(exportDir, 'data', 'public.boq_items_audit.ndjson');
      const boqPath = join(exportDir, 'data', 'public.boq_items.ndjson');
      if (!existsSync(auditPath) || !existsSync(boqPath)) {
        report.warnings.push('audit-history: export NDJSON for boq_items/boq_items_audit not found — baseline skipped.');
      } else {
        const boqIds = new Set();
        for await (const r of readNdjson(boqPath)) boqIds.add(r.id);
        let pTotal = 0, pOrphan = 0;
        const pDistinct = new Set();
        for await (const r of readNdjson(auditPath)) {
          pTotal++;
          if (!boqIds.has(r.boq_item_id)) { pOrphan++; pDistinct.add(r.boq_item_id); }
        }
        const { rows: [yt] } = await client.query('SELECT COUNT(*)::bigint AS n FROM public.boq_items_audit');
        const { rows: [yo] } = await client.query(`
          SELECT COUNT(*) FILTER (WHERE bi.id IS NULL)::bigint AS orphan_rows,
                 COUNT(DISTINCT a.boq_item_id) FILTER (WHERE bi.id IS NULL)::bigint AS distinct_orphan
            FROM public.boq_items_audit a
            LEFT JOIN public.boq_items bi ON bi.id = a.boq_item_id`);
        const prod = { total: pTotal, orphan_rows: pOrphan, distinct_orphan: pDistinct.size };
        const yandex = {
          total: Number(yt.n),
          orphan_rows: Number(yo.orphan_rows),
          distinct_orphan: Number(yo.distinct_orphan),
        };
        const total_ok = yandex.total === prod.total;
        const orphan_ok = yandex.orphan_rows === prod.orphan_rows;
        const distinct_ok = yandex.distinct_orphan === prod.distinct_orphan;
        const ok = total_ok && orphan_ok && distinct_ok;
        report.audit_history = {
          prod, yandex, total_ok, orphan_ok, distinct_ok, ok,
          note: ok ? null
            : (yandex.total === 0
                ? 'Yandex boq_items_audit is empty — table not (re)imported yet.'
                : 'Yandex audit baseline differs from PROD export — diagnose before any re-import.'),
        };
        console.log(`${tag('YA')} ${ok ? '✓' : '✗'} audit-history: prod(t=${prod.total},o=${prod.orphan_rows},d=${prod.distinct_orphan}) yandex(t=${yandex.total},o=${yandex.orphan_rows},d=${yandex.distinct_orphan})`);
      }
    } catch (e) { report.warnings.push(`audit-history check: ${safeErr(e)}`); }

    // ---- Status ----
    const hasCountFail = report.row_counts.some((r) => r.severity === 'FAIL');
    const hasFkFail = report.fk_violations.some((r) => !r.ok);
    const hasOrphanFail = report.orphan_checks.some((r) => !r.ok);
    const hasChecksumMismatch = report.checksums.some((c) => c.status === 'mismatch');
    const hasRegistryDup = report.registry_duplicates && !report.registry_duplicates.ok;
    const hasAuditInflation = report.audit_delta && !report.audit_delta.ok;
    const hasAuditHistoryFail = report.audit_history && !report.audit_history.ok;
    const hasCountWarn = report.row_counts.some((r) => r.severity === 'WARN');

    if (hasCountFail || hasFkFail || hasOrphanFail || hasChecksumMismatch || hasRegistryDup || hasAuditInflation || hasAuditHistoryFail) {
      report.status = STATUS.FAILED;
    } else if (report.warnings.length > 0 || hasCountWarn) {
      report.status = STATUS.WARN;
    } else {
      report.status = STATUS.OK;
    }
    writeReport(report);
    console.log(`${tag('YA')} status: ${report.status}`);
    console.log(`  report: ${REPORT}`);
    if (report.status === STATUS.FAILED) process.exit(1);
  } finally {
    await client.end().catch(() => {});
  }
}

main().catch((e) => {
  try {
    writeReport({ status: STATUS.FAILED, generated_at: new Date().toISOString(), note: `unexpected error: ${safeErr(e)}` });
  } catch { /* ignore */ }
  fatal(e);
});
