#!/usr/bin/env node
// 02_verify_schema — READ-ONLY verification of the Yandex schema foundation
// after apply. Only SELECT / catalog reads. Never CREATE/DROP/ALTER/INSERT.
//
// SAFETY:
//   - Read-only. NEVER prints DSN, password, cert, or full host.
//   - If env is missing or the DB is unreachable / not yet applied, emits a
//     CLEAR SCHEMA_VERIFY_FAILED status + message — never a stack trace.
//   - Writes docs/yandex-migration/09_SCHEMA_VERIFY_RESULT.md every run.
//
// Usage: npm run prod-to-yandex:verify-schema
// Env:   scripts/prod-to-yandex/.env.prod-to-yandex (see .example)

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import {
  loadEnv, env, maskHost, safeErr, resolveCa, connectStrict,
  SQL_DIR, DOC_DIR,
} from './_lib.mjs';

const REPORT = join(DOC_DIR, '09_SCHEMA_VERIFY_RESULT.md');

const STATUS = {
  OK: 'SCHEMA_VERIFY_OK',
  WARN: 'SCHEMA_VERIFY_OK_WITH_WARNINGS',
  FAILED: 'SCHEMA_VERIFY_FAILED',
};

const KEY_TABLES = [
  'users', 'roles', 'tenders', 'tender_registry', 'client_positions',
  'boq_items', 'boq_items_audit', 'import_sessions', 'notifications',
  'projects', 'cost_redistribution_results', 'tender_iterations',
];
const KEY_FUNCTIONS = [
  'handle_updated_at', 'recalculate_tender_grand_total',
  'get_positions_with_costs', 'save_redistribution_results', 'register_user',
  'log_boq_items_changes', 'bulk_import_client_position_boq',
  'execute_version_transfer',
];
const PGNOTIFY_TABLES = [
  'tenders', 'notifications', 'boq_items', 'client_positions',
  'cost_redistribution_results', 'construction_cost_volumes',
];
const SUPABASE_INTERNAL_SCHEMAS = [
  'realtime', 'storage', 'vault', 'graphql', 'supabase_migrations',
];

// Parse the foundation files so "expected" stays in sync with db/yandex/sql.
function expectedTables() {
  try {
    const sql = readFileSync(join(SQL_DIR, '03_tables.sql'), 'utf8');
    return [...sql.matchAll(/CREATE TABLE IF NOT EXISTS\s+public\.(\w+)/gi)]
      .map((m) => m[1]);
  } catch { return []; }
}
function expectedEnums() {
  try {
    const sql = readFileSync(join(SQL_DIR, '02_enums.sql'), 'utf8');
    return [...sql.matchAll(/CREATE TYPE\s+public\.(\w+)\s+AS ENUM/gi)]
      .map((m) => m[1]);
  } catch { return []; }
}

const sections = []; // { title, lines: [] }
const warnings = [];
const blockers = [];
function sec(title, lines) { sections.push({ title, lines }); }

function writeReport(status, note) {
  mkdirSync(DOC_DIR, { recursive: true });
  const L = [];
  L.push('# 09. SCHEMA VERIFY RESULT');
  L.push('');
  L.push('> Generated by `scripts/prod-to-yandex/02_verify_schema.mjs` (read-only).');
  L.push('> Overwritten on every run.');
  L.push('');
  L.push(`- Run (UTC): ${new Date().toISOString()}`);
  if (note) { L.push(`- Note: ${note}`); }
  L.push('');
  for (const s of sections) {
    L.push(`## ${s.title}`);
    L.push('');
    (s.lines.length ? s.lines : ['_n/a_']).forEach((x) => L.push(`- ${x}`));
    L.push('');
  }
  L.push('## Warnings');
  L.push('');
  (warnings.length ? warnings : ['_none_']).forEach((w) => L.push(`- ${warnings.length ? '⚠️ ' : ''}${w}`));
  L.push('');
  L.push('## Blockers');
  L.push('');
  (blockers.length ? blockers : ['_none_']).forEach((b) => L.push(`- ${blockers.length ? '❌ ' : ''}${b}`));
  L.push('');
  L.push('## Final status');
  L.push('');
  L.push('```');
  L.push(status);
  L.push('```');
  L.push('');
  writeFileSync(REPORT, L.join('\n'), 'utf8');
}

function bail(status, note, friendly) {
  writeReport(status, note);
  console.error(`✗ ${status}${friendly ? ` — ${friendly}` : ''}`);
  console.error(`  report: ${REPORT}`);
  process.exit(status === STATUS.FAILED ? 1 : 2);
}

async function main() {
  loadEnv();

  const yaUrl = env('YANDEX_DATABASE_URL');
  if (!yaUrl) {
    sec('Connection', ['YANDEX_DATABASE_URL not set — cannot verify.']);
    bail(STATUS.FAILED,
      'YANDEX_DATABASE_URL not configured (schema not verifiable).',
      'fill scripts/prod-to-yandex/.env.prod-to-yandex then re-run');
  }
  const ca = resolveCa();
  if (!ca.ok) {
    sec('Connection', [`Yandex CA unavailable (${ca.reason}); verify-full required.`]);
    bail(STATUS.FAILED, `Yandex CA unavailable: ${ca.reason}.`,
      'set YANDEX_SSL_ROOT_CERT or DSN sslrootcert=');
  }

  let client;
  try {
    client = await connectStrict(yaUrl, ca.pem, 'prod-to-yandex-verify-schema');
  } catch (e) {
    sec('Connection', [`Connection failed: ${safeErr(e)}`]);
    bail(STATUS.FAILED, `Connection failed: ${safeErr(e)}`,
      'Yandex target unreachable (or schema not applied yet)');
  }

  try {
    const q = async (sql, params) => (await client.query(sql, params)).rows;
    console.log(`▶ verify schema (read-only). target host=${maskHost(yaUrl)}`);

    // 1. Schemas
    const schemas = (await q(
      "SELECT nspname FROM pg_namespace WHERE nspname IN ('public','auth')"))
      .map((x) => x.nspname);
    const hasPublic = schemas.includes('public');
    const hasAuth = schemas.includes('auth');
    if (!hasPublic) blockers.push('schema "public" missing');
    if (!hasAuth) blockers.push('schema "auth" missing');
    sec('Schemas', [
      `public: ${hasPublic ? 'OK' : 'MISSING'}`,
      `auth: ${hasAuth ? 'OK' : 'MISSING'}`,
    ]);

    // 2. Auth compatibility
    const authUsers = (await q("SELECT to_regclass('auth.users') AS r"))[0].r != null;
    const authIdentities = (await q("SELECT to_regclass('auth.identities') AS r"))[0].r != null;
    const authUid = (await q(
      "SELECT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON p.pronamespace=n.oid " +
      "WHERE n.nspname='auth' AND p.proname='uid') AS e"))[0].e;
    if (!authUsers) blockers.push('auth.users missing');
    if (!authUid) blockers.push('auth.uid() function missing');
    if (!authIdentities) warnings.push('auth.identities absent (optional bridge — only a warning)');
    sec('Auth compatibility', [
      `auth.users: ${authUsers ? 'OK' : 'MISSING'}`,
      `auth.identities: ${authIdentities ? 'OK' : 'absent (optional)'}`,
      `auth.uid(): ${authUid ? 'OK' : 'MISSING'}`,
    ]);

    // 3. Public tables
    const expTables = expectedTables();
    const dbTables = (await q(
      "SELECT table_name FROM information_schema.tables " +
      "WHERE table_schema='public' AND table_type='BASE TABLE'"))
      .map((x) => x.table_name);
    const dbSet = new Set(dbTables);
    const missingExpected = expTables.filter((t) => !dbSet.has(t));
    const missingKey = KEY_TABLES.filter((t) => !dbSet.has(t));
    if (missingKey.length) blockers.push(`key public tables missing: ${missingKey.join(', ')}`);
    else if (missingExpected.length) warnings.push(`expected public tables missing: ${missingExpected.join(', ')}`);
    sec('Public tables', [
      `expected (from 03_tables.sql): ${expTables.length}`,
      `present in public: ${dbTables.length}`,
      `key tables: ${missingKey.length ? 'MISSING ' + missingKey.join(', ') : 'all present'}`,
      missingExpected.length ? `missing expected: ${missingExpected.join(', ')}` : 'all expected present',
    ]);

    // 4. Enums
    const expEnums = expectedEnums();
    const dbEnums = (await q(
      "SELECT t.typname FROM pg_type t JOIN pg_namespace n ON t.typnamespace=n.oid " +
      "WHERE n.nspname='public' AND t.typtype='e'")).map((x) => x.typname);
    const enumSet = new Set(dbEnums);
    const missingEnums = expEnums.filter((e) => !enumSet.has(e));
    if (expEnums.length && missingEnums.length) blockers.push(`enums missing: ${missingEnums.join(', ')}`);
    sec('Enums', [
      `expected (from 02_enums.sql): ${expEnums.length}`,
      `present: ${dbEnums.length}`,
      missingEnums.length ? `missing: ${missingEnums.join(', ')}` : 'all expected enums present',
    ]);

    // 5. Functions
    const notifyFn = (await q(
      "SELECT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON p.pronamespace=n.oid " +
      "WHERE n.nspname='public' AND p.proname='notify_row_change') AS e"))[0].e;
    if (!notifyFn) blockers.push('public.notify_row_change() missing');
    const fnRows = (await q(
      "SELECT p.proname FROM pg_proc p JOIN pg_namespace n ON p.pronamespace=n.oid " +
      "WHERE n.nspname='public' AND p.proname = ANY($1)", [KEY_FUNCTIONS]))
      .map((x) => x.proname);
    const missingFns = KEY_FUNCTIONS.filter((f) => !fnRows.includes(f));
    if (missingFns.length) blockers.push(`key functions missing: ${missingFns.join(', ')}`);
    sec('Functions', [
      `public.notify_row_change(): ${notifyFn ? 'OK' : 'MISSING'}`,
      `key business functions: ${missingFns.length ? 'MISSING ' + missingFns.join(', ') : 'all present'}`,
    ]);

    // 6. Triggers
    const ntRows = (await q(
      "SELECT event_object_table AS tbl FROM information_schema.triggers " +
      "WHERE trigger_schema='public' AND trigger_name LIKE 'trg_notify_row_change%'"));
    const ntSet = new Set(ntRows.map((x) => x.tbl));
    const missingNotify = PGNOTIFY_TABLES.filter((t) => !ntSet.has(t));
    if (missingNotify.length) blockers.push(`pg_notify rowchange triggers missing on: ${missingNotify.join(', ')}`);
    const updTrg = (await q(
      "SELECT count(*)::int AS n FROM information_schema.triggers " +
      "WHERE trigger_schema='public' AND action_statement ILIKE '%handle_updated_at%'"))[0].n;
    if (Number(updTrg) === 0) warnings.push('no updated_at (handle_updated_at) triggers found');
    sec('Triggers', [
      `pg_notify rowchange triggers: ${missingNotify.length ? 'MISSING ' + missingNotify.join(', ') : 'all 6 present'}`,
      `updated_at triggers (handle_updated_at): ${updTrg}`,
    ]);

    // 7. Extensions
    const exts = (await q("SELECT extname FROM pg_extension")).map((x) => x.extname);
    for (const e of ['pgcrypto', 'uuid-ossp']) {
      if (!exts.includes(e)) blockers.push(`extension "${e}" not enabled`);
    }
    sec('Extensions', [
      `pgcrypto: ${exts.includes('pgcrypto') ? 'OK' : 'MISSING'}`,
      `uuid-ossp: ${exts.includes('uuid-ossp') ? 'OK' : 'MISSING'}`,
      `all: ${exts.join(', ') || '(none)'}`,
    ]);

    // 8. Supabase internal schemas absent
    const present = (await q(
      "SELECT nspname FROM pg_namespace WHERE nspname = ANY($1)",
      [SUPABASE_INTERNAL_SCHEMAS])).map((x) => x.nspname);
    if (present.length) blockers.push(`Supabase-internal schema(s) present: ${present.join(', ')}`);
    sec('Supabase internal schemas', [
      present.length ? `PRESENT (must be absent): ${present.join(', ')}` :
        `absent (OK): ${SUPABASE_INTERNAL_SCHEMAS.join(', ')}`,
    ]);

    // 9. Row counts (all app tables + auth.* must be 0 after schema apply)
    const rcLines = [];
    let nonZero = 0;
    for (const t of dbTables) {
      const c = Number((await q(`SELECT count(*)::bigint AS n FROM public."${t}"`))[0].n);
      if (c !== 0) { nonZero++; rcLines.push(`public.${t} = ${c} (EXPECTED 0)`); }
    }
    if (authUsers) {
      const c = Number((await q('SELECT count(*)::bigint AS n FROM auth.users'))[0].n);
      if (c !== 0) { nonZero++; rcLines.push(`auth.users = ${c} (EXPECTED 0)`); }
    }
    if (authIdentities) {
      const c = Number((await q('SELECT count(*)::bigint AS n FROM auth.identities'))[0].n);
      if (c !== 0) { nonZero++; rcLines.push(`auth.identities = ${c} (EXPECTED 0)`); }
    }
    if (nonZero > 0) blockers.push(`${nonZero} table(s) not empty after schema apply (no data import expected at this stage)`);
    sec('Row counts', nonZero === 0
      ? [`all ${dbTables.length} public tables + auth.* are empty (0 rows) — OK`]
      : rcLines);

    // 10. RLS (no active Supabase policies)
    const pols = await q(
      "SELECT schemaname, tablename, policyname, roles::text AS roles, " +
      "COALESCE(qual,'') AS qual, COALESCE(with_check,'') AS wc " +
      "FROM pg_policies WHERE schemaname IN ('public','auth')");
    if (pols.length === 0) {
      sec('RLS', ['no policies present — OK (access control is enforced by Go BFF)']);
    } else {
      const lines = [];
      let supabaseLike = 0;
      for (const p of pols) {
        const sb = /auth\.uid|\bauthenticated\b|\banon\b|\bservice_role\b/i
          .test(`${p.roles} ${p.qual} ${p.wc}`);
        if (sb) supabaseLike++;
        lines.push(`${p.schemaname}.${p.tablename}: ${p.policyname}${sb ? ' (Supabase-like)' : ''}`);
      }
      sec('RLS', lines);
      if (supabaseLike > 0) blockers.push(`${supabaseLike} Supabase-like RLS policy(ies) present (must not be ported)`);
      else warnings.push(`${pols.length} non-Supabase RLS policy(ies) present — review`);
    }
  } catch (e) {
    sec('Verification', [`unexpected query failure: ${safeErr(e)}`]);
    blockers.push(`verification aborted: ${safeErr(e)}`);
  } finally {
    await client.end().catch(() => {});
  }

  let status;
  if (blockers.length) status = STATUS.FAILED;
  else if (warnings.length) status = STATUS.WARN;
  else status = STATUS.OK;

  writeReport(status);

  console.log('\nSummary:');
  for (const s of sections) {
    console.log(`  [${s.title}] ${s.lines[0] || ''}`);
  }
  if (blockers.length) {
    console.error(`\nBlockers (${blockers.length}):`);
    blockers.forEach((b) => console.error(`  ✗ ${b}`));
  }
  if (warnings.length) {
    console.error(`\nWarnings (${warnings.length}):`);
    warnings.forEach((w) => console.error(`  ⚠ ${w}`));
  }
  const sym = status === STATUS.OK ? '✓' : status === STATUS.WARN ? '⚠' : '✗';
  console.log(`\n${sym} ${status} — report: ${REPORT}`);
  process.exit(status === STATUS.FAILED ? 1 : 0);
}

main().catch((e) => {
  // Friendly top-level handler — no stack trace unless DEBUG=true.
  try {
    sec('Fatal', [safeErr(e)]);
    blockers.push(`unexpected error: ${safeErr(e)}`);
    writeReport(STATUS.FAILED);
  } catch { /* ignore report write failure */ }
  console.error(`✗ SCHEMA_VERIFY_FAILED — unexpected error: ${safeErr(e)}`);
  if (process.env.DEBUG === 'true' && e?.stack) console.error(e.stack);
  process.exit(1);
});
