#!/usr/bin/env node
// 06_verify_passwords — verify auth.users.encrypted_password preservation
// PROD Supabase → Yandex, byte-for-byte, WITHOUT ever printing a hash.
//
// =============================== SAFETY ====================================
//  - Compares PROD (from auth.users.ndjson export) vs Yandex auth.users by
//    sha256 fingerprint only. The hash content NEVER leaves comparePasswords.
//  - Counts users with / without encrypted_password.
//  - Checks auth.users id/email sets; checks auth.identities if present.
//  - Optional bcrypt smoke (MIGRATION_SMOKE_EMAIL / MIGRATION_SMOKE_PASSWORD):
//    fetch the target hash from YANDEX auth.users and bcrypt-compare LOCALLY.
//    Yandex has NO GoTrue, so we never call a Supabase Auth endpoint. If no
//    bcrypt module is installed, the smoke is skipped with a clear warning
//    (it is optional and downgrades status to OK_WITH_WARNINGS only when the
//    smoke was requested but unavailable).
//  - OLD_SUPABASE_DB_URL forbidden (assertNoOldEnv, exit 7).
//  - Writes docs/yandex-migration/14_YANDEX_AUTH_VERIFY_RESULT.md with final
//    status YANDEX_AUTH_VERIFY_OK / _OK_WITH_WARNINGS / _FAILED.
//  - No stack trace unless DEBUG=true. Exit: 0 ok/warn · 1 failed · 2 precond.
// ===========================================================================

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

import {
  loadEnv, env, requireEnv, getExportDir, getYandexClient, resolveCa,
  tag, parseCliArgs, fatal, assertNoOldEnv, redactEmail, DOC_DIR, safeErr,
} from './_lib.mjs';
import { readNdjson } from './_copy.mjs';
import { compareEncryptedPasswords } from './_checksums.mjs';

loadEnv();

const REPORT = join(DOC_DIR, '14_YANDEX_AUTH_VERIFY_RESULT.md');
const STATUS = {
  OK: 'YANDEX_AUTH_VERIFY_OK',
  WARN: 'YANDEX_AUTH_VERIFY_OK_WITH_WARNINGS',
  FAILED: 'YANDEX_AUTH_VERIFY_FAILED',
};

const { values } = parseCliArgs({
  name: '06_verify_passwords.mjs',
  description: 'Verify auth.users.encrypted_password preservation PROD → Yandex (sha256 only).',
  options: {
    'export-dir': { type: 'string', default: '', describe: 'Override EXPORT_DIR env' },
  },
});
const exportDir = values['export-dir'] || env('EXPORT_DIR') || getExportDir();

function writeReport(report) {
  mkdirSync(DOC_DIR, { recursive: true });
  const L = [];
  L.push('# 14. YANDEX AUTH VERIFY RESULT');
  L.push('');
  L.push('> Generated by `scripts/prod-to-yandex/06_verify_passwords.mjs`.');
  L.push('> Encrypted password hashes are NEVER printed — only aggregate counts.');
  L.push('');
  L.push(`- Run (UTC): ${report.generated_at}`);
  if (report.note) L.push(`- Note: ${report.note}`);
  L.push('');
  if (report.password_compare) {
    const p = report.password_compare;
    L.push('## Password byte-to-byte (sha256 fingerprint)');
    L.push('');
    L.push('| Metric | Count |');
    L.push('|---|---:|');
    L.push(`| Total PROD rows | ${p.total} |`);
    L.push(`| Match | ${p.match} |`);
    L.push(`| Mismatch | ${p.mismatch} |`);
    L.push(`| Missing in Yandex | ${p.missing_in_yandex} |`);
    L.push(`| Both NULL (OAuth-only) | ${p.both_null} |`);
    L.push(`| PROD with password | ${p.with_password} |`);
    L.push(`| PROD without password | ${p.without_password} |`);
    L.push('');
  }
  if (report.set_comparison) {
    const s = report.set_comparison;
    L.push('## auth.users id / email sets');
    L.push('');
    L.push('| Set | PROD | Yandex | Equal |');
    L.push('|---|---:|---:|---|');
    L.push(`| id | ${s.prod_ids} | ${s.yandex_ids} | ${s.ids_equal ? '✓' : '✗'} |`);
    L.push(`| email | ${s.prod_emails} | ${s.yandex_emails} | ${s.emails_equal ? '✓' : '✗'} |`);
    L.push(`- ids missing in Yandex: **${s.ids_missing}** · ids extra in Yandex: **${s.ids_extra}**`);
    L.push('');
  }
  if (report.identities) {
    const i = report.identities;
    L.push('## auth.identities');
    L.push('');
    L.push(i.present
      ? `- PROD identities user_ids: ${i.prod_user_ids} · Yandex identities user_ids: ${i.yandex_user_ids} · equal: ${i.user_ids_equal ? '✓' : '✗'}`
      : '- auth.identities not used / not present — skipped.');
    L.push('');
  }
  L.push('## bcrypt smoke (optional, local — Yandex has no GoTrue)');
  L.push('');
  if (report.smoke) {
    L.push(`- email_masked: \`${report.smoke.email_masked}\``);
    L.push(`- result: ${report.smoke.ok ? '✓ password matches Yandex hash' : (report.smoke.skipped ? '⚠ skipped' : '✗ mismatch')}`);
    if (report.smoke.reason) L.push(`- note: ${report.smoke.reason}`);
  } else {
    L.push('Not requested (MIGRATION_SMOKE_EMAIL / MIGRATION_SMOKE_PASSWORD not set).');
  }
  L.push('');
  if (report.warnings && report.warnings.length) {
    L.push('## Warnings');
    L.push('');
    for (const w of report.warnings) L.push(`- ⚠️ ${w}`);
    L.push('');
  }
  L.push('## Final status');
  L.push('');
  L.push('```');
  L.push(report.status);
  L.push('```');
  L.push('');
  writeFileSync(REPORT, L.join('\n'), 'utf8');
}

function bail(status, friendly, exitCode) {
  writeReport({ status, generated_at: new Date().toISOString(), note: friendly });
  console.error(`✗ ${status}${friendly ? ` — ${friendly}` : ''}`);
  console.error(`  report: ${REPORT}`);
  process.exit(exitCode);
}

// sha256 compare of every PROD password row vs Yandex auth.users. Hashes are
// only read inside this scope and only passed to compareEncryptedPasswords.
async function comparePasswords(client, usersPath) {
  const r = {
    total: 0, match: 0, mismatch: 0, missing_in_yandex: 0, both_null: 0,
    with_password: 0, without_password: 0,
  };
  for await (const row of readNdjson(usersPath)) {
    r.total++;
    if (row.encrypted_password == null) r.without_password++;
    else r.with_password++;
    const { rows } = await client.query('SELECT encrypted_password FROM auth.users WHERE id = $1', [row.id]);
    if (rows.length === 0) { r.missing_in_yandex++; continue; }
    const yaPw = rows[0]?.encrypted_password ?? null;
    if (row.encrypted_password == null && yaPw == null) { r.both_null++; continue; }
    if (compareEncryptedPasswords(row.encrypted_password, yaPw)) r.match++;
    else r.mismatch++;
  }
  return r;
}

async function compareSets(client, usersPath) {
  const prodIds = new Set();
  const prodEmails = new Set();
  for await (const row of readNdjson(usersPath)) {
    prodIds.add(row.id);
    if (row.email) prodEmails.add(row.email);
  }
  const { rows } = await client.query('SELECT id, email FROM auth.users');
  const yaIds = new Set(rows.map((x) => x.id));
  const yaEmails = new Set(rows.filter((x) => x.email).map((x) => x.email));
  const idsMissing = [...prodIds].filter((i) => !yaIds.has(i)).length;
  const idsExtra = [...yaIds].filter((i) => !prodIds.has(i)).length;
  return {
    prod_ids: prodIds.size, yandex_ids: yaIds.size,
    prod_emails: prodEmails.size, yandex_emails: yaEmails.size,
    ids_equal: idsMissing === 0 && idsExtra === 0,
    emails_equal: [...prodEmails].every((e) => yaEmails.has(e)) && yaEmails.size === prodEmails.size,
    ids_missing: idsMissing, ids_extra: idsExtra,
  };
}

async function loadBcrypt() {
  for (const mod of ['bcryptjs', 'bcrypt']) {
    try {
      const m = await import(mod);
      return { mod, lib: m.default ?? m };
    } catch { /* try next */ }
  }
  return null;
}

async function main() {
  try { assertNoOldEnv(); } catch (e) { console.error(`✗ ${e.message}`); process.exit(7); }

  const usersPath = join(exportDir, 'data', 'auth.users.ndjson');
  if (!existsSync(join(exportDir, 'manifest.json'))) {
    bail(STATUS.FAILED, `manifest.json not found in ${exportDir} — run \`npm run prod-to-yandex:export\` then \`:import\` first.`, 2);
  }

  let yaUrl;
  try { yaUrl = requireEnv('YANDEX_DATABASE_URL'); }
  catch (e) { bail(STATUS.FAILED, e.message, 2); }
  const ca = resolveCa();
  if (!ca.ok) bail(STATUS.FAILED, `Yandex CA unavailable (${ca.reason}); verify-full required.`, 2);

  let client;
  try {
    client = await getYandexClient(yaUrl, ca.pem, { applicationName: 'prod-to-yandex-verify-pw' });
  } catch (e) {
    bail(STATUS.FAILED, `Yandex unreachable: ${safeErr(e)}`, 1);
  }

  const report = {
    generated_at: new Date().toISOString(),
    password_compare: null, set_comparison: null, identities: null, smoke: null,
    warnings: [], status: 'PENDING',
  };

  try {
    if (!existsSync(usersPath)) {
      report.warnings.push('auth.users.ndjson not present in export — password compare skipped.');
    } else {
      report.password_compare = await comparePasswords(client, usersPath);
      const p = report.password_compare;
      console.log(`${tag('YA')} passwords: total=${p.total} match=${p.match} mismatch=${p.mismatch} missing=${p.missing_in_yandex} both_null=${p.both_null}`);
      report.set_comparison = await compareSets(client, usersPath);
      const s = report.set_comparison;
      console.log(`${tag('YA')} auth.users sets: ids_equal=${s.ids_equal} emails_equal=${s.emails_equal} (missing=${s.ids_missing} extra=${s.ids_extra})`);
    }

    // auth.identities (optional bridge).
    try {
      const identPath = join(exportDir, 'data', 'auth.identities.ndjson');
      const { rows: yi } = await client.query('SELECT DISTINCT user_id FROM auth.identities');
      const yaUserIds = new Set(yi.map((r) => r.user_id));
      let prodUserIds = new Set();
      if (existsSync(identPath)) {
        for await (const row of readNdjson(identPath)) if (row.user_id) prodUserIds.add(row.user_id);
      }
      report.identities = {
        present: true,
        prod_user_ids: prodUserIds.size,
        yandex_user_ids: yaUserIds.size,
        user_ids_equal: prodUserIds.size === yaUserIds.size
          && [...prodUserIds].every((u) => yaUserIds.has(u)),
      };
      console.log(`${tag('YA')} auth.identities: prod_user_ids=${prodUserIds.size} yandex_user_ids=${yaUserIds.size} equal=${report.identities.user_ids_equal}`);
    } catch {
      report.identities = { present: false };
      console.log(`${tag('YA')} auth.identities not present — skipped`);
    }

    // ---- Optional bcrypt smoke (local; Yandex has no GoTrue) ----
    const smokeEmail = env('MIGRATION_SMOKE_EMAIL');
    const smokePass = env('MIGRATION_SMOKE_PASSWORD');
    if (smokeEmail && smokePass) {
      const bc = await loadBcrypt();
      if (!bc) {
        report.smoke = { email_masked: redactEmail(smokeEmail), ok: false, skipped: true, reason: 'no bcrypt module installed (bcryptjs/bcrypt) — install one to enable the local smoke' };
        report.warnings.push('bcrypt smoke requested but no bcryptjs/bcrypt module is installed; smoke skipped.');
        console.log(`${tag('YA')} bcrypt smoke ⚠ skipped (no bcrypt module)`);
      } else {
        try {
          const { rows } = await client.query('SELECT encrypted_password FROM auth.users WHERE email = $1', [smokeEmail]);
          if (rows.length === 0 || rows[0].encrypted_password == null) {
            report.smoke = { email_masked: redactEmail(smokeEmail), ok: false, skipped: true, reason: 'smoke user has no encrypted_password on Yandex' };
            report.warnings.push('bcrypt smoke user not found / no password on Yandex.');
          } else {
            const ok = await bc.lib.compare(smokePass, rows[0].encrypted_password);
            report.smoke = { email_masked: redactEmail(smokeEmail), ok, reason: ok ? null : 'plaintext does not match the migrated bcrypt hash' };
            console.log(`${tag('YA')} bcrypt smoke (${bc.mod}) ${ok ? '✓' : '✗'} (${redactEmail(smokeEmail)})`);
          }
        } catch (e) {
          report.smoke = { email_masked: redactEmail(smokeEmail), ok: false, skipped: true, reason: `smoke error: ${safeErr(e)}` };
          report.warnings.push(`bcrypt smoke error: ${safeErr(e)}`);
        }
      }
    }

    // ---- Status ----
    const pwOk = !report.password_compare
      || (report.password_compare.mismatch === 0 && report.password_compare.missing_in_yandex === 0);
    const setsOk = !report.set_comparison || (report.set_comparison.ids_equal && report.set_comparison.emails_equal);
    const identOk = !report.identities || !report.identities.present || report.identities.user_ids_equal;
    const smokeFail = report.smoke && report.smoke.ok === false && !report.smoke.skipped;

    if (!pwOk || !setsOk || !identOk || smokeFail) report.status = STATUS.FAILED;
    else if (report.warnings.length > 0 || (report.smoke && report.smoke.skipped)) report.status = STATUS.WARN;
    else report.status = STATUS.OK;

    writeReport(report);
    console.log(`${tag('YA')} status: ${report.status}`);
    console.log(`  report: ${REPORT}`);
    if (report.status === STATUS.FAILED) process.exit(1);
  } finally {
    await client.end().catch(() => {});
  }
}

main().catch((e) => {
  try {
    writeReport({ status: STATUS.FAILED, generated_at: new Date().toISOString(), note: `unexpected error: ${safeErr(e)}` });
  } catch { /* ignore */ }
  fatal(e);
});
